"""
The only datastore in this project: Qdrant, three collections.

    ci_companies   the registry — one point per company (name, domain, seed URLs)
    ci_sources     crawl state  — one point per URL (etag, page hash, next due)
    ci_content     the corpus   — one point per chunk, the only collection with
                                  meaningful vectors and the only one ever searched

Two of those three hold no vectors worth searching. They carry a 1-dimensional
placeholder because Qdrant requires every point to have one, and they are read only by
filtered `scroll`. That is a deliberate trade: crawl state is key-value data, and
modelling it as points keeps the promise that this service depends on exactly one
database instead of adding a second one for two small tables.

Everything here is mechanism. Nothing in this module knows what a company or a page
is — that meaning lives in `sources/registry.py` and `ingest/pipeline.py`.
"""
from __future__ import annotations

import threading
import uuid
from typing import Any, Dict, Iterator, List, Optional, Sequence

from app.core.config import settings
from app.core.logging import logger

# The placeholder vector for the two non-searchable collections.
_META_VECTOR: List[float] = [1.0]
_META_DIM = 1

_client: Optional[Any] = None
_client_lock = threading.Lock()

# A UUID namespace of our own, so ids generated here can never collide with ids
# generated by another tool that happens to hash the same URL.
_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_URL, "company-intel")


# --- Connection -------------------------------------------------------------
def configured() -> bool:
    return settings.qdrant_configured


def get_client():
    """Cached client. Raises rather than returning None — callers must not guess."""
    global _client
    if not configured():
        raise RuntimeError("QDRANT_URL is not set. Copy .env.example to .env and fill it in.")
    with _client_lock:
        if _client is None:
            from qdrant_client import QdrantClient

            _client = QdrantClient(
                url=settings.QDRANT_URL,
                api_key=settings.QDRANT_API_KEY or None,
                timeout=int(settings.QDRANT_TIMEOUT_SECONDS),
            )
            logger.info(f"Qdrant connected: {settings.QDRANT_URL}")
        return _client


def reset_client() -> None:
    """Drop the cached client so the next call re-reads config. Used by tests."""
    global _client
    with _client_lock:
        _client = None


# --- Names ------------------------------------------------------------------
def COMPANIES() -> str:
    return settings.QDRANT_COMPANIES_COLLECTION


def SOURCES() -> str:
    return settings.QDRANT_SOURCES_COLLECTION


def CONTENT() -> str:
    return settings.QDRANT_CONTENT_COLLECTION


def point_id(*parts: str) -> str:
    """
    A deterministic id from any key.

    Deterministic rather than random so that re-running an ingest over unchanged input
    overwrites the same points instead of duplicating the corpus — which matters most
    when a run dies half way and has to be repeated.
    """
    return str(uuid.uuid5(_NAMESPACE, "|".join(parts)))


# --- Collection lifecycle ---------------------------------------------------
# Payload indexes are what make the filters exact and cheap. `company_id` in
# particular turns "everything for this company" into a lookup instead of a similarity
# search that could miss its own company's pages.
_INDEXES: Dict[str, Sequence[tuple]] = {
    "companies": (("company_id", "keyword"), ("domain", "keyword"), ("enabled", "bool")),
    "sources": (
        ("company_id", "keyword"),
        ("url_hash", "keyword"),
        ("page_hash", "keyword"),
        ("page_type", "keyword"),
        ("status", "keyword"),
        ("next_due_at", "float"),
    ),
    "content": (
        ("company_id", "keyword"),
        ("source_type", "keyword"),
        ("page_type", "keyword"),
        ("url_hash", "keyword"),
    ),
}


def ensure_collections() -> None:
    """
    Create whatever is missing. Safe to call on every startup.

    Never recreates. A wipe-and-reload default is what lets one loader silently delete
    another loader's data the day a second source is added, so removal in this system
    is always scoped by filter — see `delete_by_filter`.
    """
    from qdrant_client import models

    client = get_client()
    plan = (
        (COMPANIES(), _META_DIM, models.Distance.DOT, _INDEXES["companies"]),
        (SOURCES(), _META_DIM, models.Distance.DOT, _INDEXES["sources"]),
        (CONTENT(), settings.EMBED_DIM, models.Distance.COSINE, _INDEXES["content"]),
    )
    for name, dim, distance, indexes in plan:
        if not client.collection_exists(name):
            client.create_collection(
                collection_name=name,
                vectors_config=models.VectorParams(size=dim, distance=distance),
            )
            logger.info(f"Created collection '{name}' ({dim}d, {distance}).")
        for field, schema in indexes:
            try:
                client.create_payload_index(
                    collection_name=name, field_name=field, field_schema=schema
                )
            except Exception:
                pass  # Qdrant has no create-index-if-absent; a duplicate is a no-op.


def verify_content_dimension() -> Optional[str]:
    """
    Confirm the live collection matches EMBED_DIM.

    A mismatch means the embedding model was changed after the collection was built.
    Every write would then fail and every read would be meaningless, so this is
    reported at startup rather than discovered on the first query.
    """
    try:
        info = get_client().get_collection(CONTENT())
        actual = info.config.params.vectors.size
        if int(actual) != int(settings.EMBED_DIM):
            return (
                f"'{CONTENT()}' was built at {actual}d but EMBED_DIM is "
                f"{settings.EMBED_DIM}. Rebuild the collection or restore the model."
            )
    except Exception as e:
        return f"Could not inspect '{CONTENT()}': {e}"
    return None


def drop_all() -> None:
    """Remove every collection. Tests and a deliberate operator reset only."""
    client = get_client()
    for name in (COMPANIES(), SOURCES(), CONTENT()):
        if client.collection_exists(name):
            client.delete_collection(name)
            logger.info(f"Dropped collection '{name}'.")


def count(collection: str, flt: Optional[Any] = None) -> int:
    try:
        return int(get_client().count(collection, count_filter=flt, exact=True).count)
    except Exception as e:
        logger.warning(f"Count failed on '{collection}': {e}")
        return 0


# --- Filters ----------------------------------------------------------------
def match_filter(**equals: Any) -> Any:
    """`match_filter(company_id="acme", source_type="website")` -> a Qdrant AND filter."""
    from qdrant_client import models

    conditions = [
        models.FieldCondition(key=key, match=models.MatchValue(value=value))
        for key, value in equals.items()
        if value is not None
    ]
    return models.Filter(must=conditions) if conditions else None


def any_filter(field: str, values: Sequence[Any]) -> Any:
    """A single `field IN (...)` condition, for narrowing to a set of companies."""
    from qdrant_client import models

    if not values:
        return None
    return models.Filter(
        must=[models.FieldCondition(key=field, match=models.MatchAny(any=list(values)))]
    )


def due_filter(now_ts: float) -> Any:
    """Live URLs whose next refresh has come due."""
    from qdrant_client import models

    return models.Filter(
        must=[
            models.FieldCondition(key="status", match=models.MatchValue(value="live")),
            models.FieldCondition(key="next_due_at", range=models.Range(lte=now_ts)),
        ]
    )


# --- Writing ----------------------------------------------------------------
def upsert(collection: str, points: Sequence[Dict[str, Any]], batch: int = 64) -> int:
    """
    Write points, batched.

    Batched because one request carrying every vector of a large site is the request
    that times out on a slow link, and a failure there loses the whole page set rather
    than one batch of it.
    """
    from qdrant_client import models

    if not points:
        return 0
    client = get_client()
    written = 0
    for start in range(0, len(points), batch):
        chunk = points[start:start + batch]
        client.upsert(
            collection_name=collection,
            points=[
                models.PointStruct(
                    id=p["id"],
                    vector=p.get("vector") or list(_META_VECTOR),
                    payload=p["payload"],
                )
                for p in chunk
            ],
            wait=True,
        )
        written += len(chunk)
    return written


def upsert_meta(collection: str, point_key: str, payload: Dict[str, Any]) -> str:
    """Write one placeholder-vector point (registry or crawl state) and return its id."""
    pid = point_id(collection, point_key)
    upsert(collection, [{"id": pid, "vector": list(_META_VECTOR), "payload": payload}])
    return pid


def delete_by_filter(collection: str, flt: Any) -> None:
    """
    Scoped removal — the only deletion this system performs.

    Used before every page write: a page that shrank from nine chunks to four would
    otherwise leave chunks five to nine in the index forever, answering questions from
    text the page no longer contains. Deterministic ids overwrite, they do not delete.
    """
    from qdrant_client import models

    if flt is None:
        raise ValueError("Refusing an unfiltered delete.")
    get_client().delete(
        collection_name=collection,
        points_selector=models.FilterSelector(filter=flt),
        wait=True,
    )


# --- Reading ----------------------------------------------------------------
def scroll(
    collection: str,
    flt: Optional[Any] = None,
    limit: int = 1000,
    with_vectors: bool = False,
) -> Iterator[Dict[str, Any]]:
    """
    Page through payloads. Vectors are excluded by default — the metadata collections
    have nothing worth transferring, and refresh only ever compares hashes.
    """
    client = get_client()
    offset = None
    while True:
        points, offset = client.scroll(
            collection_name=collection,
            scroll_filter=flt,
            limit=limit,
            offset=offset,
            with_payload=True,
            with_vectors=with_vectors,
        )
        for p in points:
            yield {"id": str(p.id), "payload": dict(p.payload or {})}
        if offset is None:
            break


def search(
    vector: Sequence[float],
    limit: int = 24,
    flt: Optional[Any] = None,
    min_similarity: Optional[float] = None,
) -> List[Dict[str, Any]]:
    """
    Similarity search over the content collection.

    A filter here only ever NARROWS the search; it never replaces it. Relevance is
    decided by meaning, and `company_id` is there to answer "...but only for Acme",
    not to turn this into a keyword lookup wearing a vector's clothes.
    """
    client = get_client()
    floor = settings.min_similarity if min_similarity is None else min_similarity
    response = client.query_points(
        collection_name=CONTENT(),
        query=list(vector),
        query_filter=flt,
        limit=limit,
        with_payload=True,
        score_threshold=floor,
    )
    return [
        {"id": str(p.id), "score": float(p.score), "payload": dict(p.payload or {})}
        for p in response.points
    ]


def health() -> Dict[str, Any]:
    """A status summary that never raises, so a dead store still renders in the UI."""
    if not configured():
        return {
            "configured": False,
            "reachable": False,
            "collections": {},
            "detail": "QDRANT_URL is not set.",
        }
    try:
        client = get_client()
        collections = {}
        for name in (COMPANIES(), SOURCES(), CONTENT()):
            collections[name] = count(name) if client.collection_exists(name) else None
        return {
            "configured": True,
            "reachable": True,
            "collections": collections,
            "detail": verify_content_dimension() or "",
        }
    except Exception as e:
        return {"configured": True, "reachable": False, "collections": {}, "detail": str(e)}
